apiVersion: v1
kind: ServiceAccount
metadata:
  name: restricted-sa
  namespace: app-team
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sa-restricted-role
  namespace: app-team
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-restricted-binding
  namespace: app-team
subjects:
- kind: ServiceAccount
  name: restricted-sa
  namespace: app-team
roleRef:
  kind: Role
  name: sa-restricted-role
  apiGroup: rbac.authorization.k8s.io

